### ISSUE TITLE
Tickets Upload PDF

### ISSUE THREAD

**Issue by lankchilled** [vincekruger/afrikaburn-app-feedback#1]
On the ticket page have the option to upload PDF from files in addition to taking a photo.

**Comment by vincekruger** [comment]
Added.

**Comment by lankchilled** [comment]
I still only see upload from camera roll. NB you can’t delete / remove an image you have uploaded. On 31 Mar 2024, at 23:12, Vince Kruger ***@***.***> wrote:﻿
Added.

**Comment by vincekruger** [comment]
You will be able to test it in the next release 😎
