### ISSUE TITLE
WTF Guide and Map says 2023

### ISSUE THREAD

**Issue by beegee44** [vincekruger/afrikaburn-app-feedback#17]
Hi, firstly, THANK YOU for creating the wonderful app!

Under ‘More Stuff’ the WTF Guide and Map say 2023. If the info is from 2023 could you please update it to 2024 info, otherwise change tab descriptions. 

Worried that once at event we won’t be able to download latest info as there is no connection there. 

Many thanks!
Bruce

**Comment by vincekruger** [comment]
@beegee44 The 2024 data is already pre-loaded on your device and will become available when the burn starts. :)
