### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by donov96** [vincekruger/afrikaburn-app-feedback#2]
**When clicking on the take photo tab, It will enter the camera and as soon as you exit back to the ticker page, the app gets a black screen and doesn't resolve itself. you need to close the app session and reopen it.**

**To Reproduce**
1. Go to 'ticket page'
2. Click on 'any of the document icons'
3. Select the 'camera icon'
4. See error when going back to app from camera.

**Expected behavior**
A black screen will appear and can only be resolved by closing current session and opening a new one.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Iphone 12]
 - OS: [e.g. iOS16.1]
 - Version [16.1.2]

**Additional context**

**Comment by donov96** [comment]
https://github.com/vincekruger/afrikaburn-app-feedback/assets/46047805/87041892-184e-4ffd-b4ef-211e3d182cdc

**Comment by vincekruger** [comment]
Resolved
