### ISSUE TITLE
Close Icon in article page

### ISSUE THREAD

**Issue by donov96** [vincekruger/afrikaburn-app-feedback#3]
** The close icon button when viewing an article is sometimes hard to find as it fades in with the background image.

**A solution would be to move it a bit higher up to the left of the screen as to avoid confusion.

![example 2](https://github.com/vincekruger/afrikaburn-app-feedback/assets/46047805/afb21074-ea1e-4018-9af4-16d880cd41ef)
![Example 1](https://github.com/vincekruger/afrikaburn-app-feedback/assets/46047805/6a654e4a-795f-41ff-a330-ffe9091e1169)

**Comment by vincekruger** [comment]
we are working on this.
