### ISSUE TITLE
Ticket Page back button Black screen 

### ISSUE THREAD

**Issue by donov96** [vincekruger/afrikaburn-app-feedback#4]
* When opening the ticket page and selection the back arrow in the top left, a black screen appears.

**To Reproduce**
1. Go to 'ticket page'
2. Click on 'back arrow in the top left'
3. See black screen.

**Expected behavior**
A black screen will appear and the app session will have to be closed and reopened 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone12]
 - OS: [e.g. iOS16.1]
 - Version [16.1.2]

**Additional context**

**Comment by donov96** [comment]
![IMG_8109](https://github.com/vincekruger/afrikaburn-app-feedback/assets/46047805/cebc4058-f132-4c43-9ef2-5f2bd5cd7377)

**Comment by vincekruger** [comment]
The back button isn't supposed to be there. I've removed the code.
