### ISSUE TITLE
Delete Ticket

### ISSUE THREAD

**Issue by lankchilled** [vincekruger/afrikaburn-app-feedback#5]
Delete ticket button not removing uploaded document.

**Comment by vincekruger** [comment]
It's so intermittent that I struggle to replicate this :(

**Comment by vincekruger** [comment]
Are you able to still view the ticket you just tried to delete?

**Comment by lankchilled** [comment]
Yes. I am.

**Comment by vincekruger** [comment]
Is it a PDF or an image?

**Comment by lankchilled** [comment]
Image.

I want to delete my image to try upload a pdf

**Comment by vincekruger** [comment]
Resolved
